server:
  port: 8080

spring:
  application:
    name: resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/.well-known/jwks.json
          issuer-uri: http://localhost:9000
          audiences: hello-api


